name: Metrics
on:
  # Schedule daily updates
  # minute, hour, day of the month, 
  schedule: [{cron: "0 23 */7 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.token }}
